---
title: "multiRMTS analysis"
author: "Sanja Alex Mike"
date: "7/22/2019"
output:
  html_document: default
  pdf_document: default
---

Preliminaries for analysis.

```{r}
library(tidyverse)
library(here)
library(langcog)
library(ggthemes)
```

Now load data. 

```{r}
d_raw <- read_csv(here("data/RMTS.csv"))
```

Reformat to long format. 

```{r}
d <- d_raw %>%
  filter(!is.na(subject)) %>%
  select(-`Hesitation (trial numbers)`, -`Left/Right Bias`,
         -SameAvg, -DiffAvg, -`GeneralNotes`,
         -RulePreseveration, -`Explanation?`) %>%
  gather(trial_type, correct, same_1:diff_3) %>%
  separate(trial_type, c("trial_type", "trial_num"))
```


By trial type.

```{r}
ms <- d %>%
  group_by(trial_type) %>%
  multi_boot_standard(col = "correct", na.rm = TRUE)

ggplot(ms, 
       aes(x = trial_type, y = mean, col = trial_type)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) + 
  ylim(0,1) + 
  ylab("Proportion correct") + 
  xlab("Trial type") + 
  geom_hline(yintercept = .5, lty = 2)  +
  theme_classic() + 
  ggthemes::scale_color_solarized() + 
  theme(legend.position = "bottom")

```

By trial type and trial number.

```{r}
ms <- d %>%
  group_by(trial_type, trial_num) %>%
  multi_boot_standard(col = "correct", na.rm = TRUE)

ggplot(ms, 
       aes(x = trial_num, y = mean, col = trial_type)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(aes(group = trial_type)) + 
  ylim(0,1) + 
  ylab("Proportion correct") + 
  xlab("Trial type") + 
  geom_hline(yintercept = .5, lty = 2) +
  theme_classic() + 
  ggthemes::scale_color_solarized() + 
  theme(legend.position = "bottom")

```
